### PR TITLE
Hello-rails-react

### PR DESCRIPTION
**Pull request by username-forGithub**
Set up a "Hello world" project as one app with Webpack

- Created a table for storing your messages and create 5 different greetings.
- Created an API endpoint that selects a random greeting from your table.
- Created a static view to be the root of the app.
- Created an App component with react-router and render it in the static view.
- Created the Greeting component that displays a greeting.
- Created a store, an action, and a reducer that connects to the API endpoint to get the random greeting.
- Display the random greeting using the Greeting component.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @username-forGithub 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow proper Gitflow and the future features section is missing in your readme

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by username-forGithub** [comment]
Hi, @prolajumokeoni.
Can you let me know what kind of gitflow I have missed?

**Comment by username-forGithub** [comment]
I think it is not good idea to stop the project from approving because of this kind of none essential things.

**Comment by prolajumokeoni** [comment]
Hi @username-forGithub, Kindly check the project[ requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md#opening-pull-requests) you are to follow Git flow which is you need to create a pull request to compare your feature branch with the development branch (dev- feature branch), please don't forget to use a descriptive name for your feature branch

**Review by Lucas-Masaba — COMMENTED** [review]
# Hello @username-forGithub  👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️ 
- [ ] Deleted branch before it could be reviewed

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
